x = input ("digite algo")
print (" é um nuemro? ", x .isnumeric ())
print (" e um alfanumero (numeros e letras)? ", x . isalnum ())
print (" e um alfabetico (letras)?", x.isalpha())
print (" esta em minusculo?" , x.islower())
print ("esta em maiusculio?" , x.isupper())
print ("e somente espaco?", x.isspace())
print ("esta capitalizada (possui maiusculas e minusculas)", x. istitle())